title: My Professional CV
description: Professional CV and Resume - John Doe
url: "" # Leave empty for GitHub Pages auto-detection
baseurl: "" # Leave empty for GitHub Pages auto-detection

# Jekyll configuration
markdown: kramdown
highlighter: rouge
permalink: pretty
theme: null  # Disable default theme to use our custom layout

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO settings
author: John Doe
twitter_username: johndoe
github_username: johndoe
linkedin_username: johndoe

# Site settings
lang: en_US
timezone: America/New_York

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - _pages

# Collections (if you want to organize content)
collections:
  pages:
    output: true
    permalink: /:name/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "cv"
